"""
Error Level Analysis Module — Analyzer Layer

The ``ElaAnalyzer`` inspects the ELA processing result (metrics, suspicious
regions, and image properties) to generate forensic ``ElaObservation``
objects.  Each observation describes a specific forensic finding with a
severity and confidence level.

Observations are generated by a set of independent, composable rules.
New rules can be added without modifying the public interface.
"""

from __future__ import annotations

import logging
import time
from typing import Callable, List

from backend.modules.ela.constants import (
    AVG_ERROR_THRESHOLD,
    HIGH_ERROR_PIXEL_PERCENTAGE_THRESHOLD,
    OBS_CONSISTENT_CAMERA_COMPRESSION,
    OBS_EDITED_REGION_SUSPECTED,
    OBS_HEAVY_JPEG_ARTIFACTS,
    OBS_LOCALIZED_RECOMPRESSION,
    OBS_MULTIPLE_COMPRESSION_SIGNATURES,
    OBS_POSSIBLE_SYNTHETIC_GENERATION,
    OBS_SCREENSHOT_CHARACTERISTICS,
    OBS_UNIFORM_COMPRESSION,
    SEVERITY_HIGH,
    SEVERITY_LOW,
    SEVERITY_MEDIUM,
    STD_DEV_THRESHOLD,
    JPEG_FORMATS,
)
from backend.modules.ela.models import (
    ElaMetrics,
    ElaObservation,
    ElaProcessingResult,
    SuspiciousRegion,
)

logger = logging.getLogger("veritasx.modules.ela.analyzer")


class ElaAnalyzer:
    """Generates forensic observations from ELA processing results.

    This class is stateless and safe to reuse across requests.
    """

    def __init__(self) -> None:
        """Initialise the analyzer with all observation rules."""
        self._rules: List[Callable[[ElaProcessingResult], List[ElaObservation]]] = [
            self._rule_uniform_compression,
            self._rule_localized_recompression,
            self._rule_heavy_jpeg_artifacts,
            self._rule_multiple_compression_signatures,
            self._rule_edited_region_suspected,
            self._rule_screenshot_characteristics,
            self._rule_possible_synthetic_generation,
            self._rule_consistent_camera_compression,
        ]

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def analyze(
        self,
        processing_result: ElaProcessingResult,
        request_id: str,
    ) -> List[ElaObservation]:
        """Run all observation rules and return the generated observations.

        :param processing_result: The result of ELA processing.
        :param request_id: Request ID for tracing.
        :return: List of ``ElaObservation`` objects.
        """
        start = time.perf_counter()
        logger.info(f"[{request_id}] Starting ELA observation analysis...")

        observations: List[ElaObservation] = []

        for rule in self._rules:
            try:
                rule_observations = rule(processing_result)
                observations.extend(rule_observations)
            except Exception as exc:
                logger.warning(
                    f"[{request_id}] Observation rule '{rule.__name__}' failed: {exc}",
                    exc_info=True,
                )

        elapsed_ms = round((time.perf_counter() - start) * 1000, 2)
        logger.info(
            f"[{request_id}] Analysis complete in {elapsed_ms}ms | "
            f"Observations generated: {len(observations)}"
        )

        return observations

    # ------------------------------------------------------------------
    # Observation Rules
    # ------------------------------------------------------------------

    def _rule_uniform_compression(
        self,
        result: ElaProcessingResult,
    ) -> List[ElaObservation]:
        """Detect uniform (consistent) compression across the image.

        :param result: ELA processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # Uniform compression: low std dev, low avg error, few/no suspicious regions
        if (
            metrics.standard_deviation < STD_DEV_THRESHOLD
            and metrics.average_error < AVG_ERROR_THRESHOLD
            and len(result.suspicious_regions) <= 1
        ):
            return [ElaObservation(
                title="Uniform Compression Detected",
                description=(
                    "The JPEG compression is consistent and even across the entire image. "
                    "This is common when an image is saved once by a camera or digital software."
                ),
                severity=SEVERITY_LOW,
                confidence=0.85,
                observation_type=OBS_UNIFORM_COMPRESSION,
            )]

        return []

    def _rule_localized_recompression(
        self,
        result: ElaProcessingResult,
    ) -> List[ElaObservation]:
        """Detect localized recompression artifacts.

        :param result: ELA processing result.
        :return: List of observations.
        """
        metrics = result.metrics
        regions = result.suspicious_regions

        # Localized recompression: some regions have high error, others low
        if len(regions) > 0 and metrics.percentage_high_error_pixels < 50.0:
            return [ElaObservation(
                title="Localized Compression Differences",
                description=(
                    "Some small parts of the image have different JPEG compression compared to nearby areas. "
                    "This sometimes happens after editing or when an image is saved multiple times."
                ),
                severity=SEVERITY_MEDIUM,
                confidence=0.75,
                observation_type=OBS_LOCALIZED_RECOMPRESSION,
            )]

        return []

    def _rule_heavy_jpeg_artifacts(
        self,
        result: ElaProcessingResult,
    ) -> List[ElaObservation]:
        """Detect heavy JPEG compression artifacts.

        :param result: ELA processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # Heavy artifacts: high average error and high percentage of high-error pixels
        if (
            metrics.average_error > AVG_ERROR_THRESHOLD * 2
            and metrics.percentage_high_error_pixels > HIGH_ERROR_PIXEL_PERCENTAGE_THRESHOLD * 2
        ):
            return [ElaObservation(
                title="Heavy JPEG Compression",
                description=(
                    "Noticeable compression artifacts appear across large parts of the image. "
                    "This typically occurs when an image has been saved repeatedly or heavily compressed."
                ),
                severity=SEVERITY_MEDIUM,
                confidence=0.80,
                observation_type=OBS_HEAVY_JPEG_ARTIFACTS,
            )]

        return []

    def _rule_multiple_compression_signatures(
        self,
        result: ElaProcessingResult,
    ) -> List[ElaObservation]:
        """Detect multiple distinct compression signatures.

        :param result: ELA processing result.
        :return: List of observations.
        """
        metrics = result.metrics
        regions = result.suspicious_regions

        # Multiple signatures: high std dev with multiple distinct suspicious regions
        if (
            metrics.standard_deviation > STD_DEV_THRESHOLD
            and len(regions) >= 3
        ):
            return [ElaObservation(
                title="Multiple Compression Signatures",
                description=(
                    "Different parts of the image show distinct compression characteristics. "
                    "This pattern often appears when elements from different images are combined or saved at different quality levels."
                ),
                severity=SEVERITY_HIGH,
                confidence=0.70,
                observation_type=OBS_MULTIPLE_COMPRESSION_SIGNATURES,
            )]

        return []

    def _rule_edited_region_suspected(
        self,
        result: ElaProcessingResult,
    ) -> List[ElaObservation]:
        """Detect a specific edited region.

        :param result: ELA processing result.
        :return: List of observations.
        """
        regions = result.suspicious_regions

        if len(regions) > 0:
            region = regions[0]  # Most intense region
            return [ElaObservation(
                title="Suspected Region Variance",
                description=(
                    "A specific area shows compression levels that differ noticeably from the rest of the image. "
                    "This region may have been modified, added, or separately re-saved."
                ),
                severity=SEVERITY_MEDIUM,
                confidence=0.65,
                observation_type=OBS_EDITED_REGION_SUSPECTED,
            )]

        return []

    def _rule_screenshot_characteristics(
        self,
        result: ElaProcessingResult,
    ) -> List[ElaObservation]:
        """Detect screenshot-like characteristics via ELA patterns.

        Screenshots captured from screen often have uniform ELA patterns
        because they are compressed once by the OS screenshot encoder.

        :param result: ELA processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # Screenshots: very low error (re-saved once, uniform compression)
        if (
            metrics.average_error < AVG_ERROR_THRESHOLD * 0.5
            and metrics.standard_deviation < STD_DEV_THRESHOLD * 0.5
            and metrics.percentage_high_error_pixels < 2.0
        ):
            return [ElaObservation(
                title="Screenshot Pattern Detected",
                description=(
                    "The image shows a very uniform, low-error compression pattern typical of screenshots captured directly from a digital display screen."
                ),
                severity=SEVERITY_LOW,
                confidence=0.70,
                observation_type=OBS_SCREENSHOT_CHARACTERISTICS,
            )]

        return []

    def _rule_possible_synthetic_generation(
        self,
        result: ElaProcessingResult,
    ) -> List[ElaObservation]:
        """Detect possible synthetic generation indicators via ELA.

        AI-generated images may show characteristic ELA patterns:
        - Very uniform low error (if generated from a model that produces
          JPEG-like output)
        - Or anomalous error distribution

        :param result: ELA processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # Synthetic indicators: extremely uniform but non-zero error
        # (suggesting the image was processed through a pipeline that
        # introduced consistent compression)
        if (
            metrics.average_error > 0
            and metrics.average_error < AVG_ERROR_THRESHOLD * 0.3
            and metrics.standard_deviation < STD_DEV_THRESHOLD * 0.3
            and metrics.percentage_high_error_pixels < 1.0
        ):
            return [ElaObservation(
                title="Unusual Compression Uniformity",
                description=(
                    "The compression pattern is unusually smooth and uniform. "
                    "Some AI image generators produce this characteristic when rendering synthetic output, though it can also occur in uncompressed digital files."
                ),
                severity=SEVERITY_MEDIUM,
                confidence=0.60,
                observation_type=OBS_POSSIBLE_SYNTHETIC_GENERATION,
            )]

        return []

    def _rule_consistent_camera_compression(
        self,
        result: ElaProcessingResult,
    ) -> List[ElaObservation]:
        """Detect consistent camera-origin compression.

        :param result: ELA processing result.
        :return: List of observations.
        """
        metrics = result.metrics
        regions = result.suspicious_regions

        # Consistent camera compression: low error, no suspicious regions, JPEG format
        if (
            result.image_format in JPEG_FORMATS
            and metrics.average_error < AVG_ERROR_THRESHOLD
            and len(regions) == 0
        ):
            return [ElaObservation(
                title="Consistent Camera Compression",
                description=(
                    "Compression characteristics are uniform across the entire image, matching what is typically seen in an original camera photograph."
                ),
                severity=SEVERITY_LOW,
                confidence=0.80,
                observation_type=OBS_CONSISTENT_CAMERA_COMPRESSION,
            )]

        return []
