"""
Error Level Analysis Module — Pydantic Data Models

Defines all data transfer objects (DTOs) used throughout the ELA module.
Models follow Pydantic v2 conventions and are serialisable to JSON for
inclusion in the standardised ``ModuleResult.data`` payload.
"""

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

class ElaConfig(BaseModel):
    """Configuration for the ELA analysis pipeline.

    Allows future configuration to switch between JPEG quality levels
    (75, 85, 90, 95) without code changes.
    """

    jpeg_quality: int = Field(
        default=90,
        ge=1,
        le=100,
        description="JPEG quality level used for re-compression during ELA",
    )

    model_config = {"extra": "forbid"}


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

class ElaMetrics(BaseModel):
    """Statistical metrics computed from the ELA difference array.

    All error values are in the 0–255 pixel-difference range.
    """

    average_error: float = Field(..., ge=0.0, description="Mean absolute pixel difference")
    maximum_error: float = Field(..., ge=0.0, description="Maximum absolute pixel difference")
    minimum_error: float = Field(..., ge=0.0, description="Minimum absolute pixel difference")
    standard_deviation: float = Field(..., ge=0.0, description="Standard deviation of pixel differences")
    high_error_pixel_count: int = Field(..., ge=0, description="Number of pixels exceeding the high-error threshold")
    percentage_high_error_pixels: float = Field(..., ge=0.0, le=100.0, description="Percentage of high-error pixels")
    mean_brightness: float = Field(..., ge=0.0, le=255.0, description="Mean brightness of the normalized ELA grayscale image")
    dynamic_range: float = Field(..., ge=0.0, le=255.0, description="Max minus min of the normalized ELA grayscale image")


# ---------------------------------------------------------------------------
# Suspicious Regions
# ---------------------------------------------------------------------------

class BoundingBox(BaseModel):
    """Axis-aligned bounding box for a suspicious region."""

    x: int = Field(..., ge=0, description="Top-left x coordinate")
    y: int = Field(..., ge=0, description="Top-left y coordinate")
    width: int = Field(..., ge=0, description="Box width in pixels")
    height: int = Field(..., ge=0, description="Box height in pixels")


class SuspiciousRegion(BaseModel):
    """A detected region with unusually high compression differences."""

    bounding_box: BoundingBox = Field(..., description="Axis-aligned bounding box")
    coordinates: List[int] = Field(..., min_length=4, max_length=4, description="[x1, y1, x2, y2] corner coordinates")
    area: float = Field(..., ge=0.0, description="Region area in pixels")
    intensity: float = Field(..., ge=0.0, description="Mean absolute difference within the region")


# ---------------------------------------------------------------------------
# Observations
# ---------------------------------------------------------------------------

class ElaObservation(BaseModel):
    """A single forensic observation generated by the ELA analyzer."""

    title: str = Field(..., description="Short, human-readable title of the observation")
    description: str = Field(..., description="Detailed explanation of what was detected")
    severity: str = Field(..., description="Severity level: 'low', 'medium', 'high', or 'critical'")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in this observation (0.0–1.0)")
    observation_type: Optional[str] = Field(default=None, description="Machine-readable observation type code")


# ---------------------------------------------------------------------------
# ELA Image Data
# ---------------------------------------------------------------------------

class ElaImageData(BaseModel):
    """Base64-encoded ELA visualization image."""

    base64: Optional[str] = Field(default=None, description="Base64-encoded PNG of the ELA image")
    format: str = Field(default="PNG", description="Image format of the base64 data")
    width: int = Field(default=0, ge=0, description="Width of the ELA image in pixels")
    height: int = Field(default=0, ge=0, description="Height of the ELA image in pixels")


# ---------------------------------------------------------------------------
# ELA Result (final structured output)
# ---------------------------------------------------------------------------

class ElaResult(BaseModel):
    """Final structured ELA analysis result included in ``ModuleResult.data``."""

    jpeg_quality: int = Field(..., description="JPEG quality used for re-compression")
    metrics: ElaMetrics = Field(..., description="Statistical metrics from the ELA analysis")
    observations: List[ElaObservation] = Field(default_factory=list, description="Generated forensic observations")
    ela_image: Optional[ElaImageData] = Field(default=None, description="Base64-encoded ELA visualization image")
    suspicious_regions: List[SuspiciousRegion] = Field(default_factory=list, description="Detected suspicious regions")
    ela_score: float = Field(..., ge=0.0, le=1.0, description="0.0 = highly suspicious, 1.0 = consistent compression")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence in the analysis")


# ---------------------------------------------------------------------------
# Internal DTOs
# ---------------------------------------------------------------------------

class ScoreResult(BaseModel):
    """Internal DTO carrying scores from the scoring engine."""

    ela_score: float = Field(..., ge=0.0, le=1.0)
    confidence_score: float = Field(..., ge=0.0, le=1.0)


class ElaProcessingResult(BaseModel):
    """Internal DTO carrying the output of the processing layer.

    Contains raw numpy arrays (allowed via arbitrary_types_allowed) that are
    consumed by the visualization, analyzer, and scorer layers.
    """

    ela_image: Any = Field(..., description="Enhanced ELA image as RGB uint8 array")
    ela_gray: Any = Field(..., description="Grayscale ELA image as uint8 array")
    diff: Any = Field(..., description="Raw absolute difference array (float64)")
    metrics: ElaMetrics = Field(..., description="Computed statistical metrics")
    suspicious_regions: List[SuspiciousRegion] = Field(default_factory=list, description="Detected suspicious regions")
    image_width: int = Field(..., ge=0, description="Original image width in pixels")
    image_height: int = Field(..., ge=0, description="Original image height in pixels")
    image_format: str = Field(..., description="Original image format (e.g. 'JPEG', 'PNG')")
    image_mode: str = Field(..., description="Original image color mode (e.g. 'RGB', 'RGBA')")

    model_config = {"arbitrary_types_allowed": True}
