"""
Metadata Analysis Module — Rule-Based Analyzer

The ``MetadataAnalyzer`` inspects extracted metadata and validation results
to generate forensic ``Observation`` objects.  Each observation describes a
specific forensic finding (e.g. "Image edited using Photoshop") with a
severity and confidence level.

Observations are generated by a set of independent, composable rules.
New rules can be added without modifying the public interface.
"""

from __future__ import annotations

import logging
import time
from typing import Callable, Dict, List, Optional

from backend.modules.metadata.constants import (
    OBS_DSLR_IMAGE,
    OBS_EDITED_PHOTOSHOP,
    OBS_EXPORTED_CANVA,
    OBS_EXPORTED_GIMP,
    OBS_GPS_REMOVED,
    OBS_METADATA_INCONSISTENT,
    OBS_METADATA_REMOVED,
    OBS_MOBILE_CAMERA,
    OBS_PNG_WITHOUT_EXIF,
    OBS_SAVED_MIDJOURNEY,
    OBS_SAVED_STABLE_DIFFUSION,
    OBS_SCREENSHOT_DETECTED,
    OBS_TIMESTAMP_MISMATCH,
    PROFESSIONAL_CAMERA_MAKES,
    SEVERITY_CRITICAL,
    SEVERITY_HIGH,
    SEVERITY_LOW,
    SEVERITY_MEDIUM,
    SOFTWARE_SIGNATURES,
    SCREENSHOT_SIGNATURES,
    MOBILE_CAMERA_MAKES,
)
from backend.modules.metadata.models import (
    ExifData,
    ExtractionResult,
    Observation,
    ValidationResult,
)
from backend.modules.metadata.utils import (
    is_future_timestamp,
    is_impossible_date,
    parse_exif_timestamp,
)

logger = logging.getLogger("veritasx.modules.metadata.analyzer")


class MetadataAnalyzer:
    """Generates forensic observations from extracted metadata.

    This class is stateless and safe to reuse across requests.
    """

    def __init__(self) -> None:
        """Initialise the analyzer with all observation rules."""
        self._rules: List[Callable[[ExtractionResult, ValidationResult], List[Observation]]] = [
            self._rule_software_signatures,
            self._rule_metadata_removed,
            self._rule_camera_missing,
            self._rule_gps_removed,
            self._rule_timestamp_mismatch,
            self._rule_screenshot_detected,
            self._rule_mobile_camera,
            self._rule_dslr_image,
            self._rule_png_without_exif,
            self._rule_metadata_inconsistent,
        ]

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def analyze(
        self,
        extraction_result: ExtractionResult,
        validation_result: ValidationResult,
        request_id: str,
    ) -> List[Observation]:
        """Run all observation rules and return the generated observations.

        :param extraction_result: The result of metadata extraction.
        :param validation_result: The result of metadata validation.
        :param request_id: Request ID for tracing.
        :return: List of ``Observation`` objects.
        """
        start = time.perf_counter()
        logger.info(f"[{request_id}] Starting metadata analysis...")

        observations: List[Observation] = []

        for rule in self._rules:
            try:
                rule_observations = rule(extraction_result, validation_result)
                observations.extend(rule_observations)
            except Exception as exc:
                logger.warning(f"[{request_id}] Observation rule '{rule.__name__}' failed: {exc}", exc_info=True)

        elapsed_ms = round((time.perf_counter() - start) * 1000, 2)
        logger.info(
            f"[{request_id}] Analysis complete in {elapsed_ms}ms | "
            f"Observations generated: {len(observations)}"
        )

        return observations

    # ------------------------------------------------------------------
    # Observation Rules
    # ------------------------------------------------------------------

    def _rule_software_signatures(
        self,
        extraction: ExtractionResult,
        validation: ValidationResult,
    ) -> List[Observation]:
        """Detect AI generators and editing software from the Software EXIF tag.

        :param extraction: Extraction result.
        :param validation: Validation result.
        :return: List of observations.
        """
        observations: List[Observation] = []
        software = extraction.exif_data.software

        if not software:
            return observations

        software_lower = software.lower()

        # Check for AI generator signatures
        for obs_type, signatures in SOFTWARE_SIGNATURES.items():
            for sig in signatures:
                if sig in software_lower:
                    observations.append(Observation(
                        title=self._format_title(obs_type),
                        description=f"Software EXIF tag contains '{sig}' signature, indicating the image was {self._format_description(obs_type)}.",
                        severity=self._severity_for(obs_type),
                        confidence=0.95,
                        observation_type=obs_type,
                    ))
                    break  # One observation per type

        return observations

    def _rule_metadata_removed(
        self,
        extraction: ExtractionResult,
        validation: ValidationResult,
    ) -> List[Observation]:
        """Detect if metadata has been completely removed.

        :param extraction: Extraction result.
        :param validation: Validation result.
        :return: List of observations.
        """
        observations: List[Observation] = []
        exif = extraction.exif_data

        if not exif.has_exif and exif.exif_field_count == 0:
            observations.append(Observation(
                title="Metadata Completely Removed",
                description=(
                    "No EXIF metadata was found in the image. "
                    "The metadata may have been stripped using tools like exiftool, "
                    "or the image was saved without metadata."
                ),
                severity=SEVERITY_HIGH,
                confidence=0.85,
                observation_type=OBS_METADATA_REMOVED,
            ))

        return observations

    def _rule_camera_missing(
        self,
        extraction: ExtractionResult,
        validation: ValidationResult,
    ) -> List[Observation]:
        """Detect if camera information is missing.

        :param extraction: Extraction result.
        :param validation: Validation result.
        :return: List of observations.
        """
        observations: List[Observation] = []
        exif = extraction.exif_data

        if exif.has_exif:
            has_make = exif.camera_make is not None and exif.camera_make != ""
            has_model = exif.camera_model is not None and exif.camera_model != ""

            if not has_make and not has_model:
                observations.append(Observation(
                    title="Camera Information Missing",
                    description=(
                        "EXIF data exists but camera make and model are not present. "
                        "This may indicate the image was processed by software that "
                        "stripped camera identification, or was generated by an AI model."
                    ),
                    severity=SEVERITY_MEDIUM,
                    confidence=0.80,
                    observation_type=OBS_CAMERA_MISSING,
                ))

        return observations

    def _rule_gps_removed(
        self,
        extraction: ExtractionResult,
        validation: ValidationResult,
    ) -> List[Observation]:
        """Detect if GPS data has been removed.

        :param extraction: Extraction result.
        :param validation: Validation result.
        :return: List of observations.
        """
        observations: List[Observation] = []
        exif = extraction.exif_data

        # Only flag if we have EXIF data but no GPS
        if exif.has_exif and exif.gps is None:
            observations.append(Observation(
                title="GPS Data Removed",
                description=(
                    "EXIF data exists but no GPS information was found. "
                    "GPS data may have been stripped for privacy reasons, "
                    "or the image was generated by an AI model that does not embed GPS."
                ),
                severity=SEVERITY_LOW,
                confidence=0.70,
                observation_type=OBS_GPS_REMOVED,
            ))

        return observations

    def _rule_timestamp_mismatch(
        self,
        extraction: ExtractionResult,
        validation: ValidationResult,
    ) -> List[Observation]:
        """Detect timestamp mismatches.

        :param extraction: Extraction result.
        :param validation: Validation result.
        :return: List of observations.
        """
        observations: List[Observation] = []
        exif = extraction.exif_data

        # Check for timestamp mismatch in validation issues
        for issue in validation.issues:
            if "differ by" in issue.description.lower() and "hour" in issue.description.lower():
                observations.append(Observation(
                    title="Timestamp Mismatch",
                    description=issue.description,
                    severity=SEVERITY_MEDIUM,
                    confidence=0.75,
                    observation_type=OBS_TIMESTAMP_MISMATCH,
                ))
                break

        # Also check for future timestamps
        from datetime import datetime
        now = datetime.now()

        for ts_field, ts_value in [
            ("DateTimeOriginal", exif.datetime_original),
            ("DateTimeDigitized", exif.datetime_digitized),
            ("DateTime", exif.datetime_modified),
        ]:
            if ts_value:
                dt = parse_exif_timestamp(ts_value)
                if dt and (is_future_timestamp(dt, now) or is_impossible_date(dt)):
                    observations.append(Observation(
                        title="Invalid Timestamp Detected",
                        description=(
                            f"EXIF {ts_field} value '{ts_value}' is invalid "
                            f"(future date or impossible date). This may indicate "
                            f"timestamp manipulation or a synthetic image."
                        ),
                        severity=SEVERITY_HIGH,
                        confidence=0.85,
                        observation_type=OBS_TIMESTAMP_MISMATCH,
                    ))
                    break  # One observation for timestamp issues

        return observations

    def _rule_screenshot_detected(
        self,
        extraction: ExtractionResult,
        validation: ValidationResult,
    ) -> List[Observation]:
        """Detect if the image is likely a screenshot.

        :param extraction: Extraction result.
        :param validation: Validation result.
        :return: List of observations.
        """
        observations: List[Observation] = []
        software = extraction.exif_data.software
        image_info = extraction.image_info

        if not software:
            return observations

        software_lower = software.lower()

        for sig in SCREENSHOT_SIGNATURES:
            if sig in software_lower:
                observations.append(Observation(
                    title="Screenshot Detected",
                    description=(
                        f"Software EXIF tag contains '{sig}' signature, "
                        "indicating this image is likely a screenshot rather than a "
                        "camera-captured photograph."
                    ),
                    severity=SEVERITY_LOW,
                    confidence=0.80,
                    observation_type=OBS_SCREENSHOT_DETECTED,
                ))
                break

        return observations

    def _rule_mobile_camera(
        self,
        extraction: ExtractionResult,
        validation: ValidationResult,
    ) -> List[Observation]:
        """Detect if the image was captured by a mobile camera.

        :param extraction: Extraction result.
        :param validation: Validation result.
        :return: List of observations.
        """
        observations: List[Observation] = []
        exif = extraction.exif_data

        if exif.camera_make:
            make_lower = exif.camera_make.lower()
            for mobile_make in MOBILE_CAMERA_MAKES:
                if mobile_make in make_lower:
                    observations.append(Observation(
                        title="Mobile Camera Image",
                        description=(
                            f"Camera make '{exif.camera_make}' indicates this image "
                            "was captured by a mobile device (smartphone/tablet)."
                        ),
                        severity=SEVERITY_LOW,
                        confidence=0.90,
                        observation_type=OBS_MOBILE_CAMERA,
                    ))
                    break

        return observations

    def _rule_dslr_image(
        self,
        extraction: ExtractionResult,
        validation: ValidationResult,
    ) -> List[Observation]:
        """Detect if the image was captured by a DSLR or professional camera.

        :param extraction: Extraction result.
        :param validation: Validation result.
        :return: List of observations.
        """
        observations: List[Observation] = []
        exif = extraction.exif_data

        if exif.camera_make:
            make_lower = exif.camera_make.lower()
            for pro_make in PROFESSIONAL_CAMERA_MAKES:
                if pro_make in make_lower:
                    observations.append(Observation(
                        title="DSLR / Professional Camera Image",
                        description=(
                            f"Camera make '{exif.camera_make}' indicates this image "
                            "was captured by a DSLR or professional camera."
                        ),
                        severity=SEVERITY_LOW,
                        confidence=0.90,
                        observation_type=OBS_DSLR_IMAGE,
                    ))
                    break

        return observations

    def _rule_png_without_exif(
        self,
        extraction: ExtractionResult,
        validation: ValidationResult,
    ) -> List[Observation]:
        """Detect PNG images without EXIF data.

        :param extraction: Extraction result.
        :param validation: Validation result.
        :return: List of observations.
        """
        observations: List[Observation] = []
        image_info = extraction.image_info
        exif = extraction.exif_data

        if image_info.format == "PNG" and not exif.has_exif:
            observations.append(Observation(
                title="PNG Without EXIF",
                description=(
                    "The image is a PNG file with no EXIF metadata. "
                    "PNG files do not natively support EXIF, but some tools "
                    "embed EXIF via the eXIf chunk. The absence of EXIF in a "
                    "PNG may indicate the image was generated or processed "
                    "without metadata."
                ),
                severity=SEVERITY_LOW,
                confidence=0.70,
                observation_type=OBS_PNG_WITHOUT_EXIF,
            ))

        return observations

    def _rule_metadata_inconsistent(
        self,
        extraction: ExtractionResult,
        validation: ValidationResult,
    ) -> List[Observation]:
        """Detect metadata inconsistencies based on validation issues.

        :param extraction: Extraction result.
        :param validation: Validation result.
        :return: List of observations.
        """
        observations: List[Observation] = []

        # If there are high or critical severity issues, flag inconsistency
        high_or_critical = [
            i for i in validation.issues
            if i.severity in (SEVERITY_HIGH, SEVERITY_CRITICAL)
        ]

        if high_or_critical:
            issue_types = [i.type for i in high_or_critical]
            observations.append(Observation(
                title="Metadata Inconsistent",
                description=(
                    f"Metadata contains {len(high_or_critical)} high/critical severity "
                    f"validation issue(s): {', '.join(issue_types)}. "
                    "The metadata may have been tampered with or is non-standard."
                ),
                severity=SEVERITY_MEDIUM,
                confidence=0.80,
                observation_type=OBS_METADATA_INCONSISTENT,
            ))

        return observations

    # ------------------------------------------------------------------
    # Helper Methods
    # ------------------------------------------------------------------

    @staticmethod
    def _format_title(obs_type: str) -> str:
        """Convert an observation type code to a human-readable title.

        :param obs_type: Observation type code (e.g. 'edited_photoshop').
        :return: Formatted title (e.g. 'Image Edited Using Photoshop').
        """
        titles: Dict[str, str] = {
            OBS_EDITED_PHOTOSHOP: "Image Edited Using Photoshop",
            OBS_EXPORTED_GIMP: "Image Exported From GIMP",
            OBS_EXPORTED_CANVA: "Image Exported Using Canva",
            OBS_SAVED_STABLE_DIFFUSION: "Image Saved Using Stable Diffusion",
            OBS_SAVED_MIDJOURNEY: "Image Saved Using Midjourney",
        }
        return titles.get(obs_type, obs_type.replace("_", " ").title())

    @staticmethod
    def _format_description(obs_type: str) -> str:
        """Convert an observation type code to a description verb.

        :param obs_type: Observation type code.
        :return: Description verb (e.g. 'edited using Photoshop').
        """
        descriptions: Dict[str, str] = {
            OBS_EDITED_PHOTOSHOP: "edited using Photoshop or Adobe software",
            OBS_EXPORTED_GIMP: "exported from GIMP",
            OBS_EXPORTED_CANVA: "exported using Canva",
            OBS_SAVED_STABLE_DIFFUSION: "saved using Stable Diffusion or a compatible AI tool",
            OBS_SAVED_MIDJOURNEY: "saved using Midjourney",
        }
        return descriptions.get(obs_type, obs_type)

    @staticmethod
    def _severity_for(obs_type: str) -> str:
        """Get the appropriate severity level for an observation type.

        :param obs_type: Observation type code.
        :return: Severity level string.
        """
        # AI generators are high severity
        if obs_type in (OBS_SAVED_STABLE_DIFFUSION, OBS_SAVED_MIDJOURNEY):
            return SEVERITY_HIGH
        # Photoshop editing is medium severity
        if obs_type == OBS_EDITED_PHOTOSHOP:
            return SEVERITY_MEDIUM
        # Other software is low severity
        return SEVERITY_LOW
