"""
Frequency Analysis Module — Analyzer Layer

The ``FrequencyAnalyzer`` inspects the FFT processing result (metrics and
image properties) to generate forensic ``FrequencyObservation`` objects.
Each observation describes a specific frequency-domain finding with a
severity and confidence level.

Observations are generated by a set of independent, composable rules.
New rules can be added without modifying the public interface.
"""

from __future__ import annotations

import logging
import time
from typing import Callable, List

from backend.modules.frequency.constants import (
    ENERGY_RATIO_HIGH_THRESHOLD,
    ENERGY_RATIO_LOW_THRESHOLD,
    HV_BALANCE_ASYMMETRY_THRESHOLD,
    MAGNITUDE_STD_HIGH_THRESHOLD,
    MAGNITUDE_STD_LOW_THRESHOLD,
    OBS_ALIASING_ARTIFACTS,
    OBS_BANDING,
    OBS_CHECKERBOARD_PATTERN,
    OBS_HIGH_FREQ_ANOMALY,
    OBS_LOW_FREQ_DOMINANT,
    OBS_NATURAL_FOOTPRINT,
    OBS_PERIODIC_STRUCTURES,
    OBS_RINGING_ARTIFACTS,
    OBS_SMOOTH_SPECTRUM,
    OBS_SPECTRAL_ASYMMETRY,
    OBS_SPECTRUM_BALANCED,
    PEAK_TO_MEAN_HIGH_THRESHOLD,
    PEAK_TO_MEAN_LOW_THRESHOLD,
    RADIAL_SYMMETRY_HIGH_THRESHOLD,
    RADIAL_SYMMETRY_LOW_THRESHOLD,
    SEVERITY_CRITICAL,
    SEVERITY_HIGH,
    SEVERITY_LOW,
    SEVERITY_MEDIUM,
    SPECTRAL_ENTROPY_HIGH_THRESHOLD,
    SPECTRAL_ENTROPY_LOW_THRESHOLD,
    JPEG_FORMATS,
    PNG_FORMATS,
    WEBP_FORMATS,
)
from backend.modules.frequency.models import (
    FrequencyMetrics,
    FrequencyObservation,
    ProcessingResult,
)

logger = logging.getLogger("veritasx.modules.frequency.analyzer")


class FrequencyAnalyzer:
    """Generates forensic observations from frequency-domain processing results.

    This class is stateless and safe to reuse across requests.
    """

    def __init__(self) -> None:
        """Initialise the analyzer with all observation rules."""
        self._rules: List[Callable[[ProcessingResult], List[FrequencyObservation]]] = [
            self._rule_periodic_structures,
            self._rule_checkerboard_pattern,
            self._rule_aliasing_artifacts,
            self._rule_high_freq_anomaly,
            self._rule_spectral_asymmetry,
            self._rule_banding,
            self._rule_ringing_artifacts,
            self._rule_spectrum_balanced,
            self._rule_low_freq_dominant,
            self._rule_smooth_spectrum,
            self._rule_natural_frequency_footprint,
        ]

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def analyze(
        self,
        processing_result: ProcessingResult,
        request_id: str,
    ) -> List[FrequencyObservation]:
        """Run all observation rules and return the generated observations.

        :param processing_result: The result of frequency processing.
        :param request_id: Request ID for tracing.
        :return: List of ``FrequencyObservation`` objects.
        """
        start = time.perf_counter()
        logger.info(f"[{request_id}] Starting frequency observation analysis...")

        observations: List[FrequencyObservation] = []

        for rule in self._rules:
            try:
                rule_observations = rule(processing_result)
                observations.extend(rule_observations)
            except Exception as exc:
                logger.warning(
                    f"[{request_id}] Frequency observation rule '{rule.__name__}' failed: {exc}",
                    exc_info=True,
                )

        elapsed_ms = round((time.perf_counter() - start) * 1000, 2)
        logger.info(
            f"[{request_id}] Analysis complete in {elapsed_ms}ms | "
            f"Observations generated: {len(observations)}"
        )

        return observations

    # ------------------------------------------------------------------
    # Observation Rules
    # ------------------------------------------------------------------

    def _rule_periodic_structures(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect periodic structures (repetitive grid/lattice patterns).

        High peak-to-mean ratios indicate strong periodic components in the
        spectrum, which can suggest checkerboard artifacts or lattice patterns
        commonly seen in AI-generated images.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # Strong periodic components: high peak-to-mean ratio with concentrated spectrum
        if metrics.peak_to_mean_ratio > PEAK_TO_MEAN_HIGH_THRESHOLD:
            confidence = min(metrics.peak_to_mean_ratio / 30.0, 0.95)
            return [FrequencyObservation(
                title="Periodic Structure Detected",
                description=(
                    "The frequency spectrum shows strong, sharp peaks at specific frequencies "
                    "(peak-to-mean ratio: {:.2f}). This indicates periodic structures or "
                    "lattice patterns that can occur in AI-generated images, digital screens, "
                    "or images with regular repeating textures. This alone does not prove "
                    "synthetic generation."
                ).format(metrics.peak_to_mean_ratio),
                severity=SEVERITY_MEDIUM,
                confidence=round(confidence, 4),
                observation_type=OBS_PERIODIC_STRUCTURES,
            )]

        return []

    def _rule_checkerboard_pattern(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect checkerboard-like frequency patterns.

        Checkerboard artifacts produce distinctive frequency spikes at the
        Nyquist frequency and its harmonics. This is characteristic of images
        that have undergone certain types of resampling or upscaling.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # Checkerboard patterns produce very high peak-to-mean ratios
        # combined with low spectral entropy (concentrated energy)
        if (
            metrics.peak_to_mean_ratio > PEAK_TO_MEAN_HIGH_THRESHOLD * 0.8
            and metrics.spectral_entropy < 0.3
        ):
            return [FrequencyObservation(
                title="Checkerboard-Like Pattern Detected",
                description=(
                    "The frequency spectrum exhibits sharp peaks with low spectral entropy "
                    "(entropy: {:.2f}, peak-to-mean: {:.2f}). This pattern is characteristic "
                    "of checkerboard artifacts, which can arise from resampling, upscaling, "
                    "or certain image generation processes. This is a forensic signal "
                    "that warrants investigation alongside other modules."
                ).format(metrics.spectral_entropy, metrics.peak_to_mean_ratio),
                severity=SEVERITY_HIGH,
                confidence=0.85,
                observation_type=OBS_CHECKERBOARD_PATTERN,
            )]

        return []

    def _rule_aliasing_artifacts(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect aliasing artifacts in the frequency spectrum.

        Aliasing produces energy at high frequencies near the Nyquist limit,
        creating characteristic "ringing" or "edge" artifacts in the spectrum.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # High-frequency anomalies with elevated outer radial energy
        if metrics.radial_energy_outer > 0.35 and metrics.energy_ratio < 2.0:
            confidence = min(metrics.radial_energy_outer * 1.5, 0.90)
            return [FrequencyObservation(
                title="High-Frequency Aliasing Detected",
                description=(
                    "The spectrum shows elevated energy in the outer (high-frequency) "
                    "region (outer radial energy: {:.1f}%). This pattern can indicate "
                    "aliasing artifacts, often caused by insufficient low-pass filtering "
                    "before downsampling, or by sharpening/scaling operations. This is "
                    "a measurable frequency-domain anomaly."
                ).format(metrics.radial_energy_outer * 100),
                severity=SEVERITY_MEDIUM,
                confidence=round(confidence, 4),
                observation_type=OBS_ALIASING_ARTIFACTS,
            )]

        return []

    def _rule_high_freq_anomaly(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect unusual high-frequency content concentration.

        Natural images typically have most energy concentrated in low
        frequencies. A spectrum with unusually high high-frequency energy
        relative to low-frequency energy may indicate synthetic generation,
        over-sharpening, or post-processing.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        if metrics.energy_ratio < ENERGY_RATIO_LOW_THRESHOLD:
            return [FrequencyObservation(
                title="Unusually High-Frequency Content",
                description=(
                    "The frequency spectrum shows an unusually flat distribution "
                    "between low and high frequencies (energy ratio: {:.2f}). "
                    "Natural photographs typically have significantly more low-frequency "
                    "energy than high-frequency energy. A flat spectrum such as this can "
                    "occur in AI-generated images or images that have been heavily "
                    "processed. This is one forensic signal and should not be "
                    "interpreted as a definitive authenticity indicator."
                ).format(metrics.energy_ratio),
                severity=SEVERITY_HIGH,
                confidence=0.75,
                observation_type=OBS_HIGH_FREQ_ANOMALY,
            )]

        return []

    def _rule_spectral_asymmetry(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect spectral asymmetry between horizontal and vertical frequencies.

        Natural images tend to have a relatively balanced distribution of
        horizontal and vertical frequency content. Significant asymmetry can
        indicate directional artifacts from specific generation or processing
        techniques.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        if metrics.hv_balance_ratio > HV_BALANCE_ASYMMETRY_THRESHOLD:
            return [FrequencyObservation(
                title="Spectral Asymmetry Detected",
                description=(
                    "The frequency spectrum shows an imbalance between horizontal and "
                    "vertical frequency energy (H/V ratio: {:.2f}:1). Natural images "
                    "typically exhibit a more balanced distribution. This asymmetry may "
                    "indicate directional artifacts from specific image processing, "
                    "generation, or compression techniques."
                ).format(metrics.hv_balance_ratio),
                severity=SEVERITY_LOW,
                confidence=0.70,
                observation_type=OBS_SPECTRAL_ASYMMETRY,
            )]

        return []

    def _rule_banding(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect banding patterns in the frequency spectrum.

        Horizontal or vertical banding produces distinct linear features
        in the FFT magnitude spectrum. These can occur from JPEG compression
        artifacts, display calibration issues, or repeated compression.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # Banding detection: look for high magnitude std combined with
        # moderate energy ratio (not extreme high or low frequency dominance)
        if (
            metrics.std_magnitude > MAGNITUDE_STD_HIGH_THRESHOLD
            and metrics.energy_ratio > ENERGY_RATIO_LOW_THRESHOLD
            and metrics.energy_ratio < ENERGY_RATIO_HIGH_THRESHOLD
        ):
            return [FrequencyObservation(
                title="Potential Banding Detected",
                description=(
                    "The frequency spectrum shows structured variations with elevated "
                    "magnitude standard deviation ({:.2f}). This can indicate banding "
                    "artifacts, which may arise from JPEG compression, colour quantisation, "
                    "or repeated image processing. The banding pattern appears as "
                    "repetitive structures in the frequency domain."
                ).format(metrics.std_magnitude),
                severity=SEVERITY_LOW,
                confidence=0.65,
                observation_type=OBS_BANDING,
            )]

        return []

    def _rule_ringing_artifacts(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect ringing artifacts in the spectrum.

        Ringing artifacts (Gibbs phenomenon) produce oscillatory patterns
        in the frequency domain that manifest as concentric ring-like
        structures around sharp features.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # Ringing: moderate spectral entropy with high magnitude std
        if (
            0.45 < metrics.spectral_entropy < 0.75
            and metrics.std_magnitude > MAGNITUDE_STD_HIGH_THRESHOLD * 0.7
            and metrics.peak_to_mean_ratio > PEAK_TO_MEAN_LOW_THRESHOLD
        ):
            return [FrequencyObservation(
                title="Ringing Artifacts Detected",
                description=(
                    "The frequency spectrum shows patterns consistent with ringing "
                    "artifacts (Gibbs phenomenon). These appear as oscillatory structures "
                    "around sharp edges in the spatial domain, which manifest as "
                    "concentric ring-like patterns in the frequency domain. This can "
                    "occur from aggressive filtering, edge enhancement, or JPEG "
                    "compression at certain quality levels."
                ),
                severity=SEVERITY_LOW,
                confidence=0.65,
                observation_type=OBS_RINGING_ARTIFACTS,
            )]

        return []

    def _rule_spectrum_balanced(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect a well-balanced frequency spectrum.

        A balanced spectrum with good low-to-high frequency energy distribution
        and reasonable entropy is characteristic of natural photographs.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        if (
            metrics.energy_ratio > ENERGY_RATIO_HIGH_THRESHOLD
            and 0.5 < metrics.spectral_entropy < 0.9
            and metrics.hv_balance_ratio < HV_BALANCE_ASYMMETRY_THRESHOLD
        ):
            confidence = min(0.5 + (metrics.spectral_entropy - 0.5) * 0.5, 0.95)
            return [FrequencyObservation(
                title="Spectrum Appears Balanced",
                description=(
                    "The frequency spectrum shows a healthy distribution of energy "
                    "across low and mid frequencies (energy ratio: {:.2f}), balanced "
                    "horizontal/vertical content (H/V ratio: {:.2f}:1), and spectral "
                    "entropy of {:.2f}. This pattern is consistent with natural "
                    "photographic content where low frequencies dominate with a smooth "
                    "roll-off to higher frequencies."
                ).format(
                    metrics.energy_ratio,
                    metrics.hv_balance_ratio,
                    metrics.spectral_entropy,
                ),
                severity=SEVERITY_LOW,
                confidence=round(confidence, 4),
                observation_type=OBS_SPECTRUM_BALANCED,
            )]

        return []

    def _rule_low_freq_dominant(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect a spectrum dominated by low frequencies.

        A spectrum where most energy is concentrated in the low-frequency
        region is typical of natural photographs, which have smooth textures
        and gradual tonal transitions.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        if (
            metrics.energy_ratio > ENERGY_RATIO_HIGH_THRESHOLD * 1.5
            and metrics.radial_energy_innner > 0.5
            and metrics.spectral_entropy > SPECTRAL_ENTROPY_LOW_THRESHOLD
        ):
            confidence = min(0.6 + metrics.radial_energy_innner * 0.4, 0.95)
            return [FrequencyObservation(
                title="Low-Frequency Dominant Spectrum",
                description=(
                    "The frequency spectrum is dominated by low-frequency content "
                    "(inner radial energy: {:.1f}%, energy ratio: {:.2f}). "
                    "This is characteristic of natural photographs where most image "
                    "structure (surfaces, lighting, large objects) resides in low "
                    "frequencies, with a smooth roll-off to higher frequencies."
                ).format(
                    metrics.radial_energy_innner * 100,
                    metrics.energy_ratio,
                ),
                severity=SEVERITY_LOW,
                confidence=round(confidence, 4),
                observation_type=OBS_LOW_FREQ_DOMINANT,
            )]

        return []

    def _rule_smooth_spectrum(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect an unusually smooth/flat frequency spectrum.

        AI-generated images often produce spectra with unusually smooth energy
        distributions because the generation process introduces subtle regularities.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # Very smooth spectrum: low magnitude std, high spectral entropy
        if (
            metrics.std_magnitude < MAGNITUDE_STD_LOW_THRESHOLD
            and metrics.spectral_entropy > SPECTRAL_ENTROPY_HIGH_THRESHOLD
            and metrics.peak_to_mean_ratio < PEAK_TO_MEAN_LOW_THRESHOLD
        ):
            return [FrequencyObservation(
                title="Unusually Smooth Spectrum",
                description=(
                    "The frequency spectrum is unusually smooth with high spectral "
                    "entropy ({:.2f}) and low magnitude variation (std: {:.2f}). "
                    "This can occur in AI-generated images where the generation "
                    "process introduces subtle regularities, or in images that have "
                    "been processed through diffusion models. This is a measurable "
                    "characteristic and should be evaluated alongside other forensic "
                    "signals."
                ).format(metrics.spectral_entropy, metrics.std_magnitude),
                severity=SEVERITY_MEDIUM,
                confidence=0.70,
                observation_type=OBS_SMOOTH_SPECTRUM,
            )]

        return []

    def _rule_natural_frequency_footprint(
        self,
        result: ProcessingResult,
    ) -> List[FrequencyObservation]:
        """Detect natural frequency-domain characteristics.

        A natural footprint includes: moderate-to-high energy ratio,
        moderate spectral entropy, reasonable magnitude std, and balanced
        HV distribution. This is the "positive" observation for natural images.

        :param result: Frequency processing result.
        :return: List of observations.
        """
        metrics = result.metrics

        # Check if this looks like a natural image's frequency footprint
        natural_score = 0
        natural_total = 0

        # 1. Low frequencies should dominate
        natural_total += 1
        if metrics.energy_ratio > ENERGY_RATIO_HIGH_THRESHOLD:
            natural_score += 1

        # 2. Spectral entropy should be moderate (not too low, not too high)
        natural_total += 1
        if 0.45 < metrics.spectral_entropy < 0.85:
            natural_score += 1

        # 3. Magnitude std should be moderate to high
        natural_total += 1
        if metrics.std_magnitude > MAGNITUDE_STD_LOW_THRESHOLD:
            natural_score += 1

        # 4. HV balance should be reasonable
        natural_total += 1
        if metrics.hv_balance_ratio < HV_BALANCE_ASYMMETRY_THRESHOLD:
            natural_score += 1

        # 5. Radial symmetry should not be too extreme
        natural_total += 1
        if (
            RADIAL_SYMMETRY_LOW_THRESHOLD
            < metrics.radial_symmetry_score
            < RADIAL_SYMMETRY_HIGH_THRESHOLD
        ):
            natural_score += 1

        # If most checks pass, this looks natural
        if natural_score >= 4 and result.image_format in JPEG_FORMATS + PNG_FORMATS + WEBP_FORMATS:
            confidence = 0.60 + (natural_score / natural_total) * 0.35
            return [FrequencyObservation(
                title="Natural Frequency Footprint",
                description=(
                    "The frequency spectrum exhibits characteristics typical of "
                    "naturally captured photography: low frequencies dominate "
                    "(energy ratio: {:.2f}), spectral entropy is moderate ({:.2f}), "
                    "and the horizontal/vertical distribution is balanced "
                    "(H/V ratio: {:.2f}:1). These characteristics are consistent "
                    "with authentic camera-captured images, though they do not "
                    "rule out all forms of digital processing."
                ).format(
                    metrics.energy_ratio,
                    metrics.spectral_entropy,
                    metrics.hv_balance_ratio,
                ),
                severity=SEVERITY_LOW,
                confidence=round(min(confidence, 0.95), 4),
                observation_type=OBS_NATURAL_FOOTPRINT,
            )]

        return []
