"""
Frequency Analysis Module — Pydantic Data Models

Defines all data transfer objects (DTOs) used throughout the Frequency Analysis
module.  Models follow Pydantic v2 conventions and are serialisable to JSON for
inclusion in the standardised ``ModuleResult.data`` payload.
"""

from __future__ import annotations

from typing import Any, List, Optional, Tuple

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Frequency Metrics
# ---------------------------------------------------------------------------

class FrequencyMetrics(BaseModel):
    """Statistical metrics computed from the frequency-domain spectrum.

    All values are derived from the 2D FFT magnitude spectrum of the
    grayscale image, after logarithmic scaling and normalisation.
    """

    # Energy distribution
    low_frequency_energy: float = Field(..., ge=0.0, description="Total energy in the low-frequency central region")
    high_frequency_energy: float = Field(..., ge=0.0, description="Total energy in the high-frequency peripheral region")
    energy_ratio: float = Field(..., ge=0.0, description="Ratio of low-frequency to high-frequency energy")
    mean_magnitude: float = Field(..., ge=0.0, description="Mean spectral magnitude (log-scaled)")
    std_magnitude: float = Field(..., ge=0.0, description="Standard deviation of spectral magnitude")
    min_magnitude: float = Field(..., ge=0.0, description="Minimum spectral magnitude (log-scaled)")
    max_magnitude: float = Field(..., ge=0.0, description="Maximum spectral magnitude (log-scaled)")

    # Spectral characteristics
    spectral_entropy: float = Field(..., ge=0.0, le=1.0, description="Normalised spectral entropy (0 = concentrated, 1 = uniform)")
    peak_to_mean_ratio: float = Field(..., ge=0.0, description="Ratio of peak magnitude to mean magnitude")

    # Radial distribution
    radial_energy_innner: float = Field(..., ge=0.0, description="Energy fraction in inner radius (0-25% of max radius)")
    radial_energy_mid: float = Field(..., ge=0.0, description="Energy fraction in mid radius (25-75% of max radius)")
    radial_energy_outer: float = Field(..., ge=0.0, description="Energy fraction in outer radius (75-100% of max radius)")

    # Directional balance
    horizontal_energy_fraction: float = Field(..., ge=0.0, le=1.0, description="Fraction of energy in horizontal frequency bands")
    vertical_energy_fraction: float = Field(..., ge=0.0, le=1.0, description="Fraction of energy in vertical frequency bands")
    hv_balance_ratio: float = Field(..., ge=0.0, description="Ratio of horizontal to vertical energy concentration")

    # Symmetry
    radial_symmetry_score: float = Field(..., ge=0.0, le=1.0, description="Measure of radial symmetry in the spectrum (0 = asymmetric, 1 = symmetric)")

    # Image properties
    image_width: int = Field(..., ge=0, description="Original image width in pixels")
    image_height: int = Field(..., ge=0, description="Original image height in pixels")
    image_format: str = Field(..., description="Original image format (e.g. 'JPEG', 'PNG')")
    image_mode: str = Field(..., description="Original image color mode")
    fft_size: Tuple[int, int] = Field(default=(512, 512), description="Dimensions of the computed FFT (rows, cols)")


# ---------------------------------------------------------------------------
# Observations
# ---------------------------------------------------------------------------

class FrequencyObservation(BaseModel):
    """A single forensic observation generated by the Frequency analyzer."""

    title: str = Field(..., description="Short, human-readable title of the observation")
    description: str = Field(..., description="Detailed explanation of what was detected")
    severity: str = Field(..., description="Severity level: 'low', 'medium', 'high', or 'critical'")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in this observation (0.0–1.0)")
    observation_type: Optional[str] = Field(default=None, description="Machine-readable observation type code")


# ---------------------------------------------------------------------------
# Visualization Data
# ---------------------------------------------------------------------------

class FrequencyImageData(BaseModel):
    """Base64-encoded FFT magnitude spectrum visualization image."""

    base64: Optional[str] = Field(default=None, description="Base64-encoded PNG of the FFT magnitude spectrum")
    format: str = Field(default="PNG", description="Image format of the base64 data")
    width: int = Field(default=0, ge=0, description="Width of the visualization in pixels")
    height: int = Field(default=0, ge=0, description="Height of the visualization in pixels")


# ---------------------------------------------------------------------------
# Frequency Result (final structured output)
# ---------------------------------------------------------------------------

class FrequencyResult(BaseModel):
    """Final structured frequency analysis result included in ``ModuleResult.data``."""

    metrics: FrequencyMetrics = Field(..., description="Computed frequency-domain metrics")
    observations: List[FrequencyObservation] = Field(default_factory=list, description="Generated forensic observations")
    fft_spectrum: Optional[FrequencyImageData] = Field(default=None, description="Base64-encoded FFT magnitude spectrum visualization")
    frequency_score: float = Field(..., ge=0.0, le=1.0, description="0.0 = suspicious/synthetic, 1.0 = consistent natural spectrum")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence in the analysis")


# ---------------------------------------------------------------------------
# Internal DTOs
# ---------------------------------------------------------------------------

class ScoreResult(BaseModel):
    """Internal DTO carrying scores from the scoring engine."""

    frequency_score: float = Field(..., ge=0.0, le=1.0, description="0.0 = suspicious, 1.0 = consistent")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence in the analysis")


class ProcessingResult(BaseModel):
    """Internal DTO carrying the output of the processing layer.

    Contains raw numpy arrays (allowed via arbitrary_types_allowed) that are
    consumed by the visualization, analyzer, and scorer layers.
    """

    magnitude_spectrum: Any = Field(..., description="Log-scaled, normalised 2D FFT magnitude spectrum (float64)")
    magnitude_original: Any = Field(..., description="Raw 2D FFT magnitude (before log scaling, float64)")
    metrics: FrequencyMetrics = Field(..., description="Computed frequency-domain metrics")
    image_width: int = Field(..., ge=0, description="Original image width in pixels")
    image_height: int = Field(..., ge=0, description="Original image height in pixels")
    image_format: str = Field(..., description="Original image format (e.g. 'JPEG', 'PNG')")
    image_mode: str = Field(..., description="Original image color mode")

    model_config = {"arbitrary_types_allowed": True}
